name: yolov4-cpu

dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv
  - pip:
    - opencv-python==4.7.0.72
    - lxml
    - tqdm
    - tensorflow==2.10.0rc0
    - absl-py
    - easydict
    - pillow
    - pytesseract